# Otto-Friedrich University of Bamberg
# Chair of Explainable Machine Learning (xAI)
# unORANIC: Unsupervised orthogonalization of anatomy and image-characteristic features
#
# @description:
# Contains all the required packages for the unORANIC project.
#
# @author: Sebastian Doerrich
# @copyright: Copyright (c) 2022, Chair of Explainable Machine Learning (xAI), Otto-Friedrich University of Bamberg
# @credits: [Sebastian Doerrich, Christian Ledig]
# @license: CC BY-SA
# @version: 1.0
# @python: Python 3
# @maintainer: Sebastian Doerrich
# @email: sebastian.doerrich@uni-bamberg.de
# @status: Production

name: unoranic
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python==3.8
  - numpy
  - scipy
  - pytorch-lightning
  - scikit-learn
  - pyyaml
  - nibabel
  - wandb
  - matplotlib
  - seaborn
  - pip
  pip:
     - albumentations
     - medmnist
     - imagecorruptions